### ISSUE TITLE
Support dependency renaming

### ISSUE THREAD

**Issue by cramertj** [alexcrichton/cargo-vendor#146]
Using cargo-vendor with a `futures-preview` dependency currently gives the following error:

```
     Running `out/cargo_vendor_target/debug/cargo-vendor vendor --sync Cargo.toml fuchsia/third_party/rust-crates/rustc_deps/vendor`
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to sync

Caused by:
  failed to load pkg lockfile

Caused by:
  no matching package named `futures_01` found (required by `futures-util-preview`)
location searched: registry https://github.com/rust-lang/crates.io-index
version required: ^0.1.25
```

**Comment by alexcrichton** [comment]
This looks like it's a bug because `cargo-vendor` is using an "outdated" version of Cargo that doesn't have the fix for reading renamed packages from the registry index. The fix is likely to "simply update `cargo`" as dependend on by cargo-vendor.

Can you test out whether https://github.com/alexcrichton/cargo-vendor/pull/147 fixes the issue for you though to confirm this hypothesis?

**Comment by cramertj** [comment]
Yup, that works for me! Thanks!

**Comment by alexcrichton** [comment]
I'll have to wait for a new release of Cargo to publish this to crates.io, but would you like a new tag to be made for the new version?

**Comment by cramertj** [comment]
No need-- I'm all set, thanks!
