### ISSUE TITLE
No good way to update vendored crate

### ISSUE THREAD

**Issue by LegNeato** [alexcrichton/cargo-vendor#23]
This is roughly my setup:

https://gist.github.com/LegNeato/793fdc3805ce67c6bd74828486fd1159

(many crates spread over the monorepo, using a shared vendor directory. A fairly common big-company scenario)

Note that this ALSO happens with a single crate in a more traditional setup.

### Issue

When I first set it up it is all working and I check it in. Everything builds and works, even on CI w/o an internet connection as it uses the shared vendor directory.

👉 No bug yet

Now, imagine I want to add a feature to `foo_crate` and it requires a new dependency `dep_crate`. I add `dep_crate` to `foo_crate`'s `[dependencies]` and.... 💣💥 .

* 👎 I can no longer `cargo build`, as `dep_crate` is not in the shared vendor directory.
* 👎 There is no way to fetch `dep_crate`, as `.cargo/config` makes all crates point to the shared vendor directory and there is no way to bypass it (and `dep_crate` is not there as it is new!).

So I end up having to do some hacks:

```sh
  # Blank the config so new deps will be downloaded from crates.io.
  mv ../../.cargo/config ../../.cargo/config.back;
  # Build to fetch from crates.io.
  cargo build;
  # Vendor newly downloaded deps to shared vendor dir.
  cargo vendor ../../third_party/rust/vendor
  # Restore the vendor config;
  mv ../../.cargo/config.back ../../.cargo/config;
```

There are lots of issues with this:
* Blanking the config is very user-hostile, but it is needed to actually get the files local.
  * Ideally there would be a way to ignore the config to pull the crates from the internet.
*  I always have to specify the `vendor` path, even if `.cargo/config` is in place.
   * It seems silly that cargo knows to read from the shared vendor dir when using `cargo build` but doesn't know how to write to it using `cargo vendor`!
* Requires a meta build system or at the very least a shell script to provide a nice developer experience.
   * Cargo should have a nice experience without needing wrapper tools.

### Suggestion

* Running `cargo vendor` with no output path in a crate that has `source.vendored-sources` set bypasses reading from `source.vendored-sources` (downloads from crates.io) and writes updated crates to `source.vendored-sources`.

**Comment by alexcrichton** [comment]
Sounds like a great suggestion to me!

**Comment by alexcrichton** [comment]
(thanks for the report!)

**Comment by nipunn1313** [comment]
I don't believe you actually have to blank your .cargo/config

When you want to add a dependency, you can do this:
1) Add dependency to Cargo.lock
2) `cargo build` (or `cargo update`). The build will fail since the dep isn't vendored yet, however the Cargo.lock will update.
3) Run `cargo vendor` using the new Lockfile

`cargo vendor` is smart enough to go to Crates io, even if you have .cargo/config set. Cargo build is not.

I do agree that this flow is not very obvious. It would be nice if cargo itself recognized that there was source replacement going on and gave a helpful suggestion (perhaps if it recognized that `cargo vendor` was being used to do the source replacement)

Also, because of #33, step 3 currently is a bit more complex, but that is a separate bug we can hopefully fix soon.

**Comment by alexcrichton** [comment]
Ok I've pushed up a fix for this which entailed a few things:

* `cargo vendor` now works over manifests instead of lockfiles (but lock files are accepted for backcompat)
* As part of its operation `cargo vendor` will now generate the lock file, basically doing version resolution.
* All `[source]` configuration in .cargo/config is ignored, and cargo-vendor should always go straight to crates.io.

I'm hoping that this means you can basically run `cargo vendor` regardless of the manifest and regardless of the state of local configuration, and it should always work! Let me know if there's any problems though!
