### ISSUE TITLE
No way to detect unused vendored crates with shared vendor directory

### ISSUE THREAD

**Issue by LegNeato** [alexcrichton/cargo-vendor#24]
When using a shared vendor directory, there is no way to detect that a vendored crate is no longer referenced. Without post-processing, the vendor directory reflects all deps over time rather than the deps needed currently.

Mozilla appears to be working around this by blowing away the vendor directory every time they add something:

https://bugzilla.mozilla.org/show_bug.cgi?id=1336528#c5

This workaround is less than ideal because:

* It needlessly uses bandwidth.
* One must run `cargo vendor /path/to/shared/vendor -s crateX` X times, which means there needs to be a central registry, everything needs to be under the same directory, we need to use `find` to look for `Cargo.toml`s, or people need to do it manually.
   * All these are non-starters with most big company codebases I have seen.
* Requires a meta build system or at the very least a shell script to provide a nice developer experience.
   * Cargo should have a nice experience without needing wrapper tools.

**Comment by alexcrichton** [comment]
Yeah so in general the behavior of `cargo-vendor` strayed a bit afield from what I originally intended. The intention is to support vendoring from multiple projects which means that there's actually no way to support this feature (because you'll never know the full suite of projects). 

In isolation though I think it makes sense for `cargo vendor` to morally blow away the vendor dir by default and rebuild it (or at least work as if that happened). We could then add a flag like `--append` to support multiple projects to simply append to the vendor dir (if necessary)

**Comment by LegNeato** [comment]
I figured as much 😄 . Now that I think about this more, I don't think it is the job of `cargo-vendor` and should be handled in a higher-level, likely company-specific, tool. Closing, sorry for wasting your time and thanks for the response!
